export class LoginDto { //DEFINE A CLASSE DE LOGIN, QUE SERÁ USADA PARA VALIDAR OS DADOS DE LOGIN DO USUÁRIO. ESSA CLASSE É UM DTO (DATA TRANSFER OBJECT) QUE DEFINE OS CAMPOS NECESSÁRIOS PARA O LOGIN, COMO EMAIL E SENHA.  
  'email': string;
  'password': string;
}
